//
// Generated file, do not edit! Created by nedtool 6.0 from veins/modules/application/blockchain/Block.msg.
//

#ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_BLOCK_M_H
#define __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_BLOCK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class Block;
}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/modules/UnicastMessage_m.h" // import veins.base.modules.UnicastMessage


namespace veins {

/**
 * Class generated from <tt>veins\modules\application\blockchain\Block.msg:19</tt> by nedtool.
 * <pre>
 * packet Block extends BaseFrame1609_4
 * {
 *     string previousBlockHash;
 *     simtime_t timestamp;
 *     int difficultyLevel;
 *     string miner;
 *     int nonce;
 * 
 *     string transactionData;
 * }
 * </pre>
 */
class VEINS_API Block : public ::veins::BaseFrame1609_4
{
  protected:
    omnetpp::opp_string previousBlockHash;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    int difficultyLevel = 0;
    omnetpp::opp_string miner;
    int nonce = 0;
    omnetpp::opp_string transactionData;

  private:
    void copy(const Block& other);

  protected:
    bool operator==(const Block&) = delete;

  public:
    Block(const char *name=nullptr, short kind=0);
    Block(const Block& other);
    virtual ~Block();
    Block& operator=(const Block& other);
    virtual Block *dup() const override {return new Block(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getPreviousBlockHash() const;
    virtual void setPreviousBlockHash(const char * previousBlockHash);
    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
    virtual int getDifficultyLevel() const;
    virtual void setDifficultyLevel(int difficultyLevel);
    virtual const char * getMiner() const;
    virtual void setMiner(const char * miner);
    virtual int getNonce() const;
    virtual void setNonce(int nonce);
    virtual const char * getTransactionData() const;
    virtual void setTransactionData(const char * transactionData);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Block& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Block& obj) {obj.parsimUnpack(b);}

}  // namespace veins


namespace omnetpp {

template<> inline veins::Block *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::Block*>(ptr.get<cObject>()); }
}  // namespace omnetpp

#endif // ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_BLOCK_M_H

