//
// Generated file, do not edit! Created by nedtool 6.0 from veins/modules/application/blockchain/PoWPackingPermission.msg.
//

#ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWPACKINGPERMISSION_M_H
#define __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWPACKINGPERMISSION_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class PoWPackingPermission;
}  // namespace veins


namespace veins {

/**
 * Class generated from <tt>veins\modules\application\blockchain\PoWPackingPermission.msg:17</tt> by nedtool.
 * <pre>
 * message PoWPackingPermission
 * {
 *     int rsuId;    // The ID of the RSU that is allowed to pack the block
 *     string hash;  // The hash for packing
 *     int nonce;    // The nonce for packing
 * }
 * </pre>
 */
class VEINS_API PoWPackingPermission : public ::omnetpp::cMessage
{
  protected:
    int rsuId = 0;
    omnetpp::opp_string hash;
    int nonce = 0;

  private:
    void copy(const PoWPackingPermission& other);

  protected:
    bool operator==(const PoWPackingPermission&) = delete;

  public:
    PoWPackingPermission(const char *name=nullptr, short kind=0);
    PoWPackingPermission(const PoWPackingPermission& other);
    virtual ~PoWPackingPermission();
    PoWPackingPermission& operator=(const PoWPackingPermission& other);
    virtual PoWPackingPermission *dup() const override {return new PoWPackingPermission(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getRsuId() const;
    virtual void setRsuId(int rsuId);
    virtual const char * getHash() const;
    virtual void setHash(const char * hash);
    virtual int getNonce() const;
    virtual void setNonce(int nonce);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PoWPackingPermission& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PoWPackingPermission& obj) {obj.parsimUnpack(b);}

}  // namespace veins


namespace omnetpp {

template<> inline veins::PoWPackingPermission *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::PoWPackingPermission*>(ptr.get<cObject>()); }
}  // namespace omnetpp

#endif // ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWPACKINGPERMISSION_M_H

