//
// Generated file, do not edit! Created by nedtool 6.0 from veins/modules/application/blockchain/PoWResult.msg.
//

#ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWRESULT_M_H
#define __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWRESULT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class PoWResult;
}  // namespace veins

#include "veins/base/modules/UnicastMessage_m.h" // import veins.base.modules.UnicastMessage


namespace veins {

/**
 * Class generated from <tt>veins\modules\application\blockchain\PoWResult.msg:18</tt> by nedtool.
 * <pre>
 * message PoWResult extends UnicastMessage
 * {
 *     int rsuId;    // The ID of the RSU that found the nonce
 *     string blockData;
 *     string hash;  // The hash that was found
 *     int nonce;    // The nonce that was found
 *     simtime_t timestamp;
 *     int difficultyLevel;
 *     int byteLength;
 * }
 * </pre>
 */
class VEINS_API PoWResult : public ::veins::UnicastMessage
{
  protected:
    int rsuId = 0;
    omnetpp::opp_string blockData;
    omnetpp::opp_string hash;
    int nonce = 0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    int difficultyLevel = 0;
    int byteLength = 0;

  private:
    void copy(const PoWResult& other);

  protected:
    bool operator==(const PoWResult&) = delete;

  public:
    PoWResult(const char *name=nullptr, short kind=0);
    PoWResult(const PoWResult& other);
    virtual ~PoWResult();
    PoWResult& operator=(const PoWResult& other);
    virtual PoWResult *dup() const override {return new PoWResult(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getRsuId() const;
    virtual void setRsuId(int rsuId);
    virtual const char * getBlockData() const;
    virtual void setBlockData(const char * blockData);
    virtual const char * getHash() const;
    virtual void setHash(const char * hash);
    virtual int getNonce() const;
    virtual void setNonce(int nonce);
    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
    virtual int getDifficultyLevel() const;
    virtual void setDifficultyLevel(int difficultyLevel);
    virtual int getByteLength() const;
    virtual void setByteLength(int byteLength);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PoWResult& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PoWResult& obj) {obj.parsimUnpack(b);}

}  // namespace veins


namespace omnetpp {

template<> inline veins::PoWResult *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::PoWResult*>(ptr.get<cObject>()); }
}  // namespace omnetpp

#endif // ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWRESULT_M_H

