//
// Generated file, do not edit! Created by nedtool 6.0 from veins/modules/application/blockchain/PoWResponse.msg.
//

#ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWRESPONSE_M_H
#define __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWRESPONSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class PoWResponse;
}  // namespace veins


namespace veins {

/**
 * Class generated from <tt>veins\modules\application\blockchain\PoWResponse.msg:16</tt> by nedtool.
 * <pre>
 * message PoWResponse
 * {
 *     string data;
 *     string hash;
 *     int nonce;
 * }
 * </pre>
 */
class VEINS_API PoWResponse : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string data;
    omnetpp::opp_string hash;
    int nonce = 0;

  private:
    void copy(const PoWResponse& other);

  protected:
    bool operator==(const PoWResponse&) = delete;

  public:
    PoWResponse(const char *name=nullptr, short kind=0);
    PoWResponse(const PoWResponse& other);
    virtual ~PoWResponse();
    PoWResponse& operator=(const PoWResponse& other);
    virtual PoWResponse *dup() const override {return new PoWResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getData() const;
    virtual void setData(const char * data);
    virtual const char * getHash() const;
    virtual void setHash(const char * hash);
    virtual int getNonce() const;
    virtual void setNonce(int nonce);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PoWResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PoWResponse& obj) {obj.parsimUnpack(b);}

}  // namespace veins


namespace omnetpp {

template<> inline veins::PoWResponse *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::PoWResponse*>(ptr.get<cObject>()); }
}  // namespace omnetpp

#endif // ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWRESPONSE_M_H

