//
// Generated file, do not edit! Created by nedtool 6.0 from veins/modules/application/blockchain/PoWRequest.msg.
//

#ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWREQUEST_M_H
#define __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class PoWRequest;
}  // namespace veins


namespace veins {

/**
 * Class generated from <tt>veins\modules\application\blockchain\PoWRequest.msg:16</tt> by nedtool.
 * <pre>
 * message PoWRequest
 * {
 *     string data;
 * }
 * </pre>
 */
class VEINS_API PoWRequest : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string data;

  private:
    void copy(const PoWRequest& other);

  protected:
    bool operator==(const PoWRequest&) = delete;

  public:
    PoWRequest(const char *name=nullptr, short kind=0);
    PoWRequest(const PoWRequest& other);
    virtual ~PoWRequest();
    PoWRequest& operator=(const PoWRequest& other);
    virtual PoWRequest *dup() const override {return new PoWRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getData() const;
    virtual void setData(const char * data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PoWRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PoWRequest& obj) {obj.parsimUnpack(b);}

}  // namespace veins


namespace omnetpp {

template<> inline veins::PoWRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::PoWRequest*>(ptr.get<cObject>()); }
}  // namespace omnetpp

#endif // ifndef __VEINS_VEINS_MODULES_APPLICATION_BLOCKCHAIN_POWREQUEST_M_H

