//
// Generated file, do not edit! Created by nedtool 6.0 from veins/base/modules/BroadcastMessage.msg.
//

#ifndef __VEINS_BROADCASTMESSAGE_M_H
#define __VEINS_BROADCASTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class BroadcastMessage;
}  // namespace veins


namespace veins {

/**
 * Class generated from <tt>veins/base/modules/BroadcastMessage.msg:16</tt> by nedtool.
 * <pre>
 * message BroadcastMessage
 * {
 *     string descrp = "Broadcast message signal";
 * }
 * </pre>
 */
class VEINS_API BroadcastMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string descrp = "Broadcast message signal";

  private:
    void copy(const BroadcastMessage& other);

  protected:
    bool operator==(const BroadcastMessage&) = delete;

  public:
    BroadcastMessage(const char *name=nullptr, short kind=0);
    BroadcastMessage(const BroadcastMessage& other);
    virtual ~BroadcastMessage();
    BroadcastMessage& operator=(const BroadcastMessage& other);
    virtual BroadcastMessage *dup() const override {return new BroadcastMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDescrp() const;
    virtual void setDescrp(const char * descrp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BroadcastMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BroadcastMessage& obj) {obj.parsimUnpack(b);}

}  // namespace veins


namespace omnetpp {

template<> inline veins::BroadcastMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::BroadcastMessage*>(ptr.get<cObject>()); }
}  // namespace omnetpp

#endif // ifndef __VEINS_BROADCASTMESSAGE_M_H

