//
// Generated file, do not edit! Created by nedtool 6.0 from ./veins/base/modules/UnicastMessage.msg.
//

#ifndef __VEINS_UNICASTMESSAGE_M_H
#define __VEINS_UNICASTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class UnicastMessage;
}  // namespace veins


namespace veins {

/**
 * Class generated from <tt>.\veins/base/modules/UnicastMessage.msg:16</tt> by nedtool.
 * <pre>
 * message UnicastMessage
 * {
 *     int targetRSUId = -1;
 *     string descrp = "Broadcast message signal";
 *     omnetpp::cMessage *data;
 * }
 * </pre>
 */
class VEINS_API UnicastMessage : public ::omnetpp::cMessage
{
  protected:
    int targetRSUId = -1;
    omnetpp::opp_string descrp = "Broadcast message signal";
    omnetpp::cMessage * data = nullptr;

  private:
    void copy(const UnicastMessage& other);

  protected:
    bool operator==(const UnicastMessage&) = delete;

  public:
    UnicastMessage(const char *name=nullptr, short kind=0);
    UnicastMessage(const UnicastMessage& other);
    virtual ~UnicastMessage();
    UnicastMessage& operator=(const UnicastMessage& other);
    virtual UnicastMessage *dup() const override {return new UnicastMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getTargetRSUId() const;
    virtual void setTargetRSUId(int targetRSUId);
    virtual const char * getDescrp() const;
    virtual void setDescrp(const char * descrp);
    virtual const omnetpp::cMessage * getData() const;
    virtual omnetpp::cMessage * getDataForUpdate() { return const_cast<omnetpp::cMessage *>(const_cast<UnicastMessage*>(this)->getData());}
    virtual void setData(omnetpp::cMessage * data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UnicastMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UnicastMessage& obj) {obj.parsimUnpack(b);}

}  // namespace veins


namespace omnetpp {

template<> inline veins::UnicastMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::UnicastMessage*>(ptr.get<cObject>()); }
}  // namespace omnetpp

#endif // ifndef __VEINS_UNICASTMESSAGE_M_H

