//
// Generated file, do not edit! Created by nedtool 6.0 from veins/modules/application/traci/RSUBasicMessage.msg.
//

#ifndef __VEINS_RSUBASICMESSAGE_M_H
#define __VEINS_RSUBASICMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class RSUBasicMessage;
}  // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/RSUBasicMessage.msg:21</tt> by nedtool.
 * <pre>
 * packet RSUBasicMessage extends BaseFrame1609_4
 * {
 *     string info;
 * }
 * </pre>
 */
class VEINS_API RSUBasicMessage : public ::veins::BaseFrame1609_4
{
  protected:
    omnetpp::opp_string info;

  private:
    void copy(const RSUBasicMessage& other);

  protected:
    bool operator==(const RSUBasicMessage&) = delete;

  public:
    RSUBasicMessage(const char *name=nullptr, short kind=0);
    RSUBasicMessage(const RSUBasicMessage& other);
    virtual ~RSUBasicMessage();
    RSUBasicMessage& operator=(const RSUBasicMessage& other);
    virtual RSUBasicMessage *dup() const override {return new RSUBasicMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getInfo() const;
    virtual void setInfo(const char * info);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RSUBasicMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RSUBasicMessage& obj) {obj.parsimUnpack(b);}

}  // namespace veins


namespace omnetpp {

template<> inline veins::RSUBasicMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::RSUBasicMessage*>(ptr.get<cObject>()); }
}  // namespace omnetpp

#endif // ifndef __VEINS_RSUBASICMESSAGE_M_H

